In [1]:
import pyterrier as pt
import requests
import pandas as pd
import pickle
import nltk
import numpy as np

In [2]:
def bibsonomy_pubs(queries):
    df = pd.DataFrame()
    for query in queries: 
        url = f"https://www.bibsonomy.org/json/search/{query}?items=1000"
        response = requests.get(url)
        
        if response.status_code == 200:  # Sicherstellen, dass die Anfrage erfolgreich ist
            data = response.json()
            if "items" in data:  # Sicherstellen, dass "items" im JSON vorhanden ist
                df_temp = pd.DataFrame.from_dict(data["items"])
                
                # Füge die Suchanfrage als Spalte hinzu
                df_temp["search_term"] = query
                
                # Filtere nur die gewünschten Spalten
                df_temp = df_temp[["id", "label", "author", "type", "date", "year", "search_term", "tags", "description", "changeDate", "url", "pub-type", "publisher"]]
                                  #Die doppelten [[]] Klammern müssen gesetzt werden um die Selection durchzuführen
                
                # Kombiniere den aktuellen DataFrame mit dem finalen DataFrame
                df = pd.concat([df, df_temp], ignore_index=True)
    return df

# Suche durchführen
df_bibsonomy = bibsonomy_pubs(["terrorism", "extremism", "islamism"])

# Ausgabe des finalen DataFrames
df_bibsonomy

,id,label,author,type,date,year,search_term,tags,description,changeDate,url,pub-type,publisher
0,https://www.bibsonomy.org/url/a864ce7a699f298b...,RAND Voices of Jihad Database (Terrorism Datab...,NaN,Bookmark,2010-06-22 21:44:54,NaN,terrorism,"[jihadist, terrorism, speeches, extremist, jih...",This online database is a compilation of speec...,2010-06-22 21:44:54,http://www.rand.org/research_areas/terrorism/d...,NaN,NaN
1,https://www.bibsonomy.org/url/5fddf40b64888908...,FRIDE - Money and terrorism,NaN,Bookmark,2014-01-07 13:18:37,NaN,terrorism,"[terrorism, money]","Loretta Napoleoni (07/01/2005) ""FRIDE is a Eur...",2014-10-14 15:29:31,http://www.fride.org/publication/93/money-and-...,NaN,NaN
2,https://www.bibsonomy.org/url/07b5970f2929a2e1...,EU Terrorism Situation & Trend Report (Te-Sat)...,NaN,Bookmark,2017-08-25 12:27:11,NaN,terrorism,"[terrorism, eu]","""Europol’s annual EU Terrorism Situation and T...",2017-08-25 12:32:17,https://www.europol.europa.eu/activities-servi...,NaN,NaN
3,https://www.bibsonomy.org/url/dff53678a84d36e9...,"Andrew Sullivan, terrorism, and the art of dis...",NaN,Bookmark,2014-01-07 13:18:36,NaN,terrorism,"[islam, imperialism, terrorism, quinn]",analysis of the concept of terrorism after the...,2014-10-14 15:29:29,http://www.guardian.co.uk/commentisfree/2013/m...,NaN,NaN
4,https://www.bibsonomy.org/url/5ad307232bdcf55c...,"MILF and terrorism: Hypocrisy, lies, truth",NaN,Bookmark,2012-10-18 14:23:57,NaN,terrorism,"[Asia, terrorism, history]","For now, it remains an agreement to agree – a ...",2012-10-18 14:23:57,http://www.rappler.com/thought-leaders/14222-m...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4489,https://www.bibsonomy.org/bibtex/2ca4013002a4a...,"Synthesis, characterization, crystal structure...","[Robabeh Alizadeh, Salma Hafezeffati, Vahid Am...",Publication,2017-05-10 15:29:29,{2015},islamism,"[Fluorescence}, Crystal, {Gold(III);, structur...",,2017-05-10 15:29:29,,article,SPRINGER WIEN
4490,https://www.bibsonomy.org/bibtex/2da18cb667b6b...,Mononuclear nickel(II) complexes coordinated b...,"[Hassan Hadadzadeh, Ghobad Mansouri, Ali Rezva...",Publication,2017-05-10 15:29:29,{2011},islamism,"[Polypyridyl, Magnetic, Nickel(II), {Polymorph...",,2017-05-10 15:29:29,,article,PERGAMON-ELSEVIER SCIENCE LTD
4491,https://www.bibsonomy.org/bibtex/283d78840230a...,"Syntheses, crystal, molecular structures, and ...","[M. Mirzaei, H. Eshtiagh-Hosseini, N. Alfi, H....",Publication,2017-05-10 15:29:29,{2011},islamism,"[studies;, Coordination, DFT}, acid;, Crystal,...",,2017-05-10 15:29:29,,article,SPRINGER/PLENUM PUBLISHERS
4492,https://www.bibsonomy.org/bibtex/2fb7edce6fd76...,La città ineguale. Pratiche culturali e organi...,[ a cura di Cattedra e Memoli],Publication,2014-04-10 00:42:49,1999,islamism,"[africa, latina, Pratiche, marginalità, urbani...",La città ineguale. Pratiche culturali e organi...,2014-04-10 19:37:58,,book,Mimesis
4493,https://www.bibsonomy.org/bibtex/2556ca293e7d6...,"Global incidence, prevalence, years lived with...","[Alize J Ferrari, Damian Francesco Santomauro,...",Publication,2024-04-19 11:49:43,2024,islamism,"[prevalence, disability, LongLIfe, LifeExpenta...",,2024-04-19 11:49:43,,article,Elsevier BV

In [5]:
df_bibsonomy = df_bibsonomy[df_bibsonomy["type"] == "Publication"]
df_bibsonomy

,id,label,author,type,date,year,search_term,tags,description,changeDate,url,pub-type,publisher
1000,https://www.bibsonomy.org/bibtex/22e03edf1449f...,Food Terrorism,[Matthew N. O. Sadiku | Sarhan M. Musa | Tolul...,Publication,2019-07-04 12:16:18,2019,terrorism,"[terrorism, biological, defense, food, agro]",,2019-07-04 12:16:18,https://www.ijtsrd.com/other-scientific-resear...,article,NaN
1001,https://www.bibsonomy.org/bibtex/26a182024b6db...,How does Terrorism Effect on Business and Rela...,[S. Raju Pooja Prof. Sidharth],Publication,2018-09-11 08:26:02,2017,terrorism,"[Business, (IB), Terrorism, business, Internat...",,2018-10-02 11:01:26,http://www.ijtsrd.com/management/international...,article,NaN
1002,https://www.bibsonomy.org/bibtex/201c2fea8172a...,Money Transfer Regulation and the Fight agains...,[Lukong Alban Bongwong],Publication,2020-10-03 11:41:39,2020,terrorism,"[Other, transfer, terrorism, corruption, Funds]",,2020-10-03 11:41:39,https://www.ijtsrd.com/other-scientific-resear...,article,NaN
1003,https://www.bibsonomy.org/bibtex/2273978ed4446...,"State terrorism in Latin America : Chile, Arge...",[Thomas Wright],Publication,2015-07-23 15:15:26,2007,terrorism,"[außenpolitik, usa, menschenrechte, politik, l...","State Terrorism in Latin America: Chile, Argen...",2020-11-20 13:41:20,http://www.amazon.de/State-Terrorism-Latin-Ame...,book,Rowman & Littlefield
1004,https://www.bibsonomy.org/bibtex/2adba8d1854b2...,The Role of Extradition Treaties in Crime Mana...,[AdishiEric OlukaNduka Lucas],Publication,2018-09-01 12:55:37,2018,terrorism,"[Extradition, Crime, Terrorism, treaties, chal...",,2018-10-02 11:01:26,http://www.ijtsrd.com/humanities-and-the-arts/...,article,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4489,https://www.bibsonomy.org/bibtex/2ca4013002a4a...,"Synthesis, characterization, crystal structure...","[Robabeh Alizadeh, Salma Hafezeffati, Vahid Am...",Publication,2017-05-10 15:29:29,{2015},islamism,"[Fluorescence}, Crystal, {Gold(III);, structur...",,2017-05-10 15:29:29,,article,SPRINGER WIEN
4490,https://www.bibsonomy.org/bibtex/2da18cb667b6b...,Mononuclear nickel(II) complexes coordinated b...,"[Hassan Hadadzadeh, Ghobad Mansouri, Ali Rezva...",Publication,2017-05-10 15:29:29,{2011},islamism,"[Polypyridyl, Magnetic, Nickel(II), {Polymorph...",,2017-05-10 15:29:29,,article,PERGAMON-ELSEVIER SCIENCE LTD
4491,https://www.bibsonomy.org/bibtex/283d78840230a...,"Syntheses, crystal, molecular structures, and ...","[M. Mirzaei, H. Eshtiagh-Hosseini, N. Alfi, H....",Publication,2017-05-10 15:29:29,{2011},islamism,"[studies;, Coordination, DFT}, acid;, Crystal,...",,2017-05-10 15:29:29,,article,SPRINGER/PLENUM PUBLISHERS
4492,https://www.bibsonomy.org/bibtex/2fb7edce6fd76...,La città ineguale. Pratiche culturali e organi...,[ a cura di Cattedra e Memoli],Publication,2014-04-10 00:42:49,1999,islamism,"[africa, latina, Pratiche, marginalità, urbani...",La città ineguale. Pratiche culturali e organi...,2014-04-10 19:37:58,,book,Mimesis
4493,https://www.bibsonomy.org/bibtex/2556ca293e7d6...,"Global incidence, prevalence, years lived with...","[Alize J Ferrari, Damian Francesco Santomauro,...",Publication,2024-04-19 11:49:43,2024,islamism,"[prevalence, disability, LongLIfe, LifeExpenta...",,2024-04-19 11:49:43,,article,Elsevier BV

In [ ]:
df_bibsonomy.rename(columns={

In [6]:
if not pt.started():
    pt.init()

/tmp/ipykernel_4644/3057724015.py:1: DeprecationWarning: Call to deprecated function (or staticmethod) started. (use pt.java.started() instead) -- Deprecated since version 0.11.0.
  if not pt.started():
Java started and loaded: pyterrier.java, pyterrier.terrier.java [version=5.11 (build: craig.macdonald 2025-01-13 21:29), helper_version=0.0.8]
/tmp/ipykernel_4644/3057724015.py:2: DeprecationWarning: Call to deprecated method pt.init(). Deprecated since version 0.11.0.
java is now started automatically with default settings. To force initialisation early, run:
pt.java.init() # optional, forces java initialisation
  pt.init()

In [7]:
#Umbenennung der Spalten zur Vorbereitung auf die Indexierung/Dokumentenrepräsentation
df_bibsonomy['docno'] = df_bibsonomy['id']
df_bibsonomy['text'] = df_bibsonomy['label']

/tmp/ipykernel_4644/967087675.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_bibsonomy['docno'] = df_bibsonomy['id']
/tmp/ipykernel_4644/967087675.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_bibsonomy['text'] = df_bibsonomy['label']

In [8]:
index_folder = "/home/tim/Schreibtisch/2024-25-Data_Librarian-Reschop_Tim/Modul_2-1/violence_index" #anlegen eines Speicherortes für unseres Index/Dokumentenrepräsentation

indexer = pt.DFIndexer(index_folder, overwrite=True) #DataFrameIndexer für die Indexierung auswählen und festlegen wo er gespeichert werden soll und das ein bereits bestehender Index überschrieben werden soll
index_ref = indexer.index(df_bibsonomy['text'], df_bibsonomy['docno']) #Festlegen, aus welchen Spalten des DF der Index erstellt wird

#Dieser Code erstellt einen IR-Index (Information Retrieval Index) aus dem DataFrame df_bibsonomy. 
#Die Spalte text enthält die Dokumentinhalte, die indexiert werden, und docno wird als eindeutige ID für jedes Dokument verwendet. 
#Mit diesem Index kannst du später Suchanfragen ausführen oder andere IR-Operationen mit PyTerrier durchführen.

print(f"path to our index: {index_ref.toString()}")

/tmp/ipykernel_4644/2736489296.py:3: DeprecationWarning: Call to deprecated class DFIndexer. (use pt.terrier.IterDictIndexer().index(dataframe.to_dict(orient='records')) instead) -- Deprecated since version 0.11.0.
  indexer = pt.DFIndexer(index_folder, overwrite=True) #DataFrameIndexer für die Indexierung auswählen und festlegen wo er gespeichert werden soll und das ein bereits bestehender Index überschrieben werden soll

path to our index: /home/tim/Schreibtisch/2024-25-Data_Librarian-Reschop_Tim/Modul_2-1/violence_index/data.properties

In [9]:
#Index-Instanz aus der zuvor erstellten Index-Referenz (index_ref) erstellen
#pt.IndexFactory: Eine Klasse in PyTerrier, die verwendet wird, um mit Indexen zu arbeiten (z. B. erstellen, laden, verwenden).
#.of(index_ref): Diese Methode erstellt ein Indexobjekt aus der Referenz (index_ref), die auf den Speicherort des Index zeigt.
#Das zurückgegebene Objekt (index) ermöglicht es dir, auf den Index zuzugreifen und Operationen wie Suchen, Abrufen von Metadaten oder Statistiken auszuführen.

index = pt.IndexFactory.of(index_ref)

#Der zuvor erstellte Index (index_ref) ist lediglich ein Verweis auf den Speicherort des Index (normalerweise ein Ordner auf der Festplatte). 
#Mit pt.IndexFactory.of() wird dieser Verweis "geladen" und als voll funktionsfähiger Index bereitgestellt.
#Erst jetzt haben wir einen Index

In [10]:
print(index.getCollectionStatistics().toString())

#.toString() wird aufgerufen, um dieses Objekt in eine lesbare String-Repräsentation zu konvertieren. 
#So kannst du die Statistiken einfach ausgeben, z. B. in der Konsole oder Logs.

Number of documents: 2790
Number of terms: 5196
Number of postings: 22565
Number of fields: 0
Number of tokens: 23179
Field names: []
Positions:   false

In [11]:
#term -> term_id Nt Tf
#Nt: In how many documents does the term occur?
#TF (Term Frequency): How often does the term occur in total?

for kv in index.getLexicon(): #gibt eine Sammlung zurück (das Lexikon), die alle Terme und ihre zugehörigen Informationen enthält.
    print(f"{kv.getKey()} -> {kv.getValue().toString()}") #kv.getValue() liefert ein Objekt, das die Statistiken oder Informationen über den Term enthält.
                                                          #.toString() gibt eine lesbare Form aus

0 -> term1707 Nt=4 TF=4 maxTF=1 @{0 0 0}
00 -> term2912 Nt=1 TF=1 maxTF=1 @{0 9 2}
03 -> term290 Nt=1 TF=1 maxTF=1 @{0 12 0}
1 -> term107 Nt=52 TF=60 maxTF=3 @{0 13 6}
10 -> term2999 Nt=8 TF=8 maxTF=1 @{0 72 2}
100 -> term2921 Nt=1 TF=1 maxTF=1 @{0 82 4}
1068 -> term4945 Nt=1 TF=1 maxTF=1 @{0 85 2}
11 -> term347 Nt=23 TF=23 maxTF=1 @{0 88 2}
11th -> term1155 Nt=2 TF=2 maxTF=1 @{0 118 2}
12 -> term2495 Nt=3 TF=3 maxTF=1 @{0 122 6}
129a -> term2013 Nt=1 TF=1 maxTF=1 @{0 130 4}
129b -> term1611 Nt=1 TF=1 maxTF=1 @{0 133 0}
12th -> term1150 Nt=1 TF=1 maxTF=1 @{0 135 4}
13 -> term3599 Nt=2 TF=2 maxTF=1 @{0 137 6}
134 -> term1673 Nt=1 TF=1 maxTF=1 @{0 143 2}
14 -> term2604 Nt=1 TF=1 maxTF=1 @{0 145 6}
1442 -> term4452 Nt=1 TF=1 maxTF=1 @{0 148 4}
14h -> term3617 Nt=1 TF=1 maxTF=1 @{0 151 4}
16 -> term2825 Nt=3 TF=3 maxTF=1 @{0 154 4}
167em -> term2911 Nt=1 TF=1 maxTF=1 @{0 162 0}
17 -> term4438 Nt=1 TF=1 maxTF=1 @{0 164 6}
1790 -> term2332 Nt=1 TF=1 maxTF=1 @{0 167 6}
1797 -> term3805 Nt=1 TF=1 maxTF=1 @{0 170 4}
18 -> term2816 Nt=3 TF=3 maxTF=1 @{0 173 4}
1825 -> term3149 Nt=1 TF=1 maxTF=1 @{0 179 6}
1837 -> term1907 Nt=3 TF=3 maxTF=1 @{0 182 4}
1842 -> term4657 Nt=1 TF=1 maxTF=1 @{0 188 2}
1871 -> term2573 Nt=2 TF=2 maxTF=1 @{0 191 2}
19 -> term1251 Nt=7 TF=7 maxTF=1 @{0 194 6}
1901 -> term2561 Nt=1 TF=1 maxTF=1 @{0 206 0}
1908 -> term3345 Nt=4 TF=4 maxTF=1 @{0 208 6}
1914 -> term2762 Nt=3 TF=3 maxTF=1 @{0 214 6}
1918 -> term2006 Nt=1 TF=1 maxTF=1 @{0 220 2}
1922 -> term1993 Nt=1 TF=1 maxTF=1 @{0 222 6}
1930 -> term4609 Nt=1 TF=1 maxTF=1 @{0 225 2}
1933 -> term2201 Nt=1 TF=1 maxTF=1 @{0 228 2}
1935 -> term4382 Nt=1 TF=1 maxTF=1 @{0 230 6}
1941 -> term2240 Nt=1 TF=1 maxTF=1 @{0 233 6}
1943 -> term77 Nt=1 TF=1 maxTF=1 @{0 236 2}
1944 -> term2244 Nt=1 TF=1 maxTF=1 @{0 237 4}
1945 -> term2200 Nt=1 TF=1 maxTF=1 @{0 240 0}
1946 -> term2559 Nt=1 TF=1 maxTF=1 @{0 242 4}
1947 -> term2976 Nt=1 TF=1 maxTF=1 @{0 245 2}
1950 -> term3086 Nt=3 TF=3 maxTF=1 @{0 248 0}
1951 -> term2504 Nt=2 TF=2 maxTF=1 @{0 255 2}
1957 -> term2472 Nt=1 TF=1 maxTF=1 @{0 259 6}
1958 -> term1210 Nt=1 TF=1 maxTF=1 @{0 262 4}
1959 -> term3078 Nt=2 TF=2 maxTF=1 @{0 264 6}
1961 -> term3146 Nt=1 TF=1 maxTF=1 @{0 269 4}
1963 -> term3706 Nt=1 TF=1 maxTF=1 @{0 272 2}
1968 -> term705 Nt=2 TF=2 maxTF=1 @{0 275 2}
1969 -> term1134 Nt=2 TF=2 maxTF=1 @{0 280 0}
1970 -> term31 Nt=7 TF=7 maxTF=1 @{0 284 4}
1970er -> term2145 Nt=1 TF=1 maxTF=1 @{0 297 0}
1972 -> term1206 Nt=2 TF=2 maxTF=1 @{0 299 4}
1974 -> term1133 Nt=1 TF=1 maxTF=1 @{0 304 0}
1975 -> term1996 Nt=1 TF=1 maxTF=1 @{0 306 2}
1977 -> term2245 Nt=1 TF=1 maxTF=1 @{0 308 6}
1978 -> term3923 Nt=2 TF=2 maxTF=1 @{0 311 2}
1979 -> term1208 Nt=4 TF=4 maxTF=1 @{0 315 4}
1980 -> term2413 Nt=2 TF=2 maxTF=1 @{0 324 6}
1981 -> term2010 Nt=1 TF=1 maxTF=1 @{0 330 2}
1982 -> term1655 Nt=1 TF=1 maxTF=1 @{0 332 6}
1984 -> term4475 Nt=2 TF=2 maxTF=1 @{0 335 2}
1985 -> term4867 Nt=1 TF=1 maxTF=1 @{0 340 2}
1986 -> term925 Nt=2 TF=2 maxTF=1 @{0 343 2}
1989 -> term4734 Nt=1 TF=1 maxTF=1 @{0 348 0}
1990 -> term4852 Nt=3 TF=3 maxTF=1 @{0 351 0}
1991 -> term2763 Nt=1 TF=1 maxTF=1 @{0 356 6}
1992 -> term1904 Nt=1 TF=1 maxTF=1 @{0 359 4}
1993 -> term1964 Nt=1 TF=1 maxTF=1 @{0 362 0}
1995 -> term3924 Nt=3 TF=3 maxTF=1 @{0 364 4}
1997 -> term696 Nt=1 TF=1 maxTF=1 @{0 370 4}
1998 -> term3906 Nt=1 TF=1 maxTF=1 @{0 372 6}
1999 -> term4474 Nt=3 TF=3 maxTF=1 @{0 375 6}
19th -> term3277 Nt=1 TF=1 maxTF=1 @{0 382 0}
1d -> term5093 Nt=1 TF=1 maxTF=1 @{0 384 6}
1h -> term3584 Nt=8 TF=8 maxTF=1 @{0 387 6}
1st -> term2178 Nt=1 TF=1 maxTF=1 @{0 400 6}
1t -> term3659 Nt=2 TF=2 maxTF=1 @{0 403 2}
1tn -> term3570 Nt=1 TF=1 maxTF=1 @{0 406 4}
2 -> term93 Nt=74 TF=137 maxTF=5 @{0 409 4}
20 -> term3270 Nt=2 TF=2 maxTF=1 @{0 477 5}
2000 -> term1487 Nt=1 TF=1 maxTF=1 @{0 482 7}
2001 -> term1131 Nt=2 TF=2 maxTF=1 @{0 485 3}
2002 -> term1029 Nt=5 TF=5 maxTF=1 @{0 489 7}
2003 -> term2598 Nt=2 TF=2 maxTF=1 @{0 499 5}
2004 -> term1338 Nt=2 TF=2 maxTF=1 @{0 505 1}
2005 -> term558 Nt=2 TF=2 maxTF=1 @{0 509 7}
2006 -> term3087 Nt=2 TF=2 maxTF=1 @{0 514 5}
2007 -> term728 Nt=1 TF=1 maxTF=1 @{0 519 7}
2008 -> term3496 Nt=4 TF=4 maxTF=1 @{0 522 1}
2009 -> term727 Nt=4 TF=4 maxTF=1 @{0 530 3}
2010 -> term1415 Nt=5 TF=5 maxTF=1 @{0 539 5}
2011 -> term3354 Nt=1 TF=1 maxTF=1 @{0 551 1}
2012 -> term2497 Nt=2 TF=2 maxTF=1 @{0 553 7}
2013 -> term1194 Nt=4 TF=5 maxTF=2 @{0 559 1}
2014 -> term3079 Nt=2 TF=2 maxTF=1 @{0 568 4}
2015 -> term859 Nt=4 TF=4 maxTF=1 @{0 573 2}
2016 -> term1737 Nt=2 TF=2 maxTF=1 @{0 583 0}
2017 -> term2817 Nt=1 TF=1 maxTF=1 @{0 588 2}
2018 -> term708 Nt=4 TF=4 maxTF=1 @{0 591 0}
2020 -> term851 Nt=5 TF=5 maxTF=1 @{0 600 6}
2021 -> term3271 Nt=2 TF=3 maxTF=2 @{0 611 2}
2022 -> term858 Nt=1 TF=1 maxTF=1 @{0 616 5}
2030 -> term3417 Nt=1 TF=1 maxTF=1 @{0 618 7}
204 -> term5194 Nt=1 TF=1 maxTF=1 @{0 621 5}
20th -> term2588 Nt=2 TF=2 maxTF=1 @{0 624 5}
21 -> term4258 Nt=1 TF=1 maxTF=1 @{0 629 5}
21st -> term951 Nt=5 TF=7 maxTF=2 @{0 632 5}
22nd -> term1407 Nt=1 TF=1 maxTF=1 @{0 642 1}
23 -> term1991 Nt=1 TF=1 maxTF=1 @{0 644 5}
26 -> term1285 Nt=2 TF=2 maxTF=1 @{0 647 1}
29 -> term4835 Nt=1 TF=1 maxTF=1 @{0 651 3}
2h -> term4046 Nt=2 TF=2 maxTF=1 @{0 654 3}
2so -> term4052 Nt=1 TF=1 maxTF=1 @{0 659 3}
3 -> term1096 Nt=26 TF=34 maxTF=4 @{0 662 3}
30 -> term2547 Nt=1 TF=1 maxTF=1 @{0 697 1}
33 -> term2753 Nt=1 TF=1 maxTF=1 @{0 699 7}
360 -> term1916 Nt=1 TF=1 maxTF=1 @{0 702 5}
371 -> term5191 Nt=1 TF=1 maxTF=1 @{0 705 1}
3d -> term3157 Nt=6 TF=6 maxTF=1 @{0 708 1}
3h -> term4045 Nt=4 TF=4 maxTF=1 @{0 720 3}
4 -> term2224 Nt=43 TF=56 maxTF=3 @{0 726 3}
41 -> term3871 Nt=1 TF=1 maxTF=1 @{0 762 4}
439 -> term4989 Nt=1 TF=1 maxTF=1 @{0 765 4}
48 -> term4808 Nt=1 TF=1 maxTF=1 @{0 768 4}
4h -> term3606 Nt=1 TF=1 maxTF=1 @{0 771 4}
4h2o -> term3605 Nt=1 TF=1 maxTF=1 @{0 774 4}
5 -> term614 Nt=30 TF=40 maxTF=3 @{0 777 4}
5h -> term4304 Nt=1 TF=1 maxTF=1 @{0 815 2}
5oh -> term4053 Nt=1 TF=1 maxTF=1 @{0 818 2}
6 -> term5021 Nt=11 TF=13 maxTF=2 @{0 821 2}
622 -> term4814 Nt=1 TF=1 maxTF=1 @{0 831 4}
646 -> term1093 Nt=1 TF=1 maxTF=1 @{0 834 4}
651 -> term4811 Nt=1 TF=1 maxTF=1 @{0 836 6}
6h -> term4306 Nt=1 TF=1 maxTF=1 @{0 839 6}
7 -> term4717 Nt=6 TF=6 maxTF=1 @{0 842 6}
70 -> term2827 Nt=1 TF=1 maxTF=1 @{0 851 6}
700 -> term3476 Nt=2 TF=2 maxTF=1 @{0 854 4}
70er -> term1399 Nt=1 TF=1 maxTF=1 @{0 860 0}
787 -> term3477 Nt=1 TF=1 maxTF=1 @{0 862 4}
8 -> term4083 Nt=3 TF=5 maxTF=2 @{0 865 4}
811 -> term5188 Nt=1 TF=1 maxTF=1 @{0 873 0}
828 -> term3806 Nt=1 TF=1 maxTF=1 @{0 876 0}
87 -> term4866 Nt=1 TF=1 maxTF=1 @{0 879 0}
8h2o -> term3867 Nt=1 TF=1 maxTF=1 @{0 882 0}
9 -> term374 Nt=10 TF=10 maxTF=1 @{0 885 0}
98 -> term1212 Nt=2 TF=2 maxTF=1 @{0 901 4}
99 -> term2560 Nt=3 TF=3 maxTF=1 @{0 906 6}
ab -> term2929 Nt=5 TF=5 maxTF=1 @{0 912 4}
abb -> term4722 Nt=1 TF=1 maxTF=1 @{0 923 6}
abbau -> term2019 Nt=1 TF=1 maxTF=1 @{0 926 6}
abd -> term4038 Nt=2 TF=2 maxTF=1 @{0 929 2}
abdarraziq -> term3675 Nt=1 TF=1 maxTF=1 @{0 934 4}
abduct -> term2865 Nt=1 TF=1 maxTF=1 @{0 937 4}
abdul -> term3448 Nt=1 TF=1 maxTF=1 @{0 940 2}
abdurahman -> term4396 Nt=1 TF=1 maxTF=1 @{0 943 2}
abhandlung -> term4229 Nt=1 TF=1 maxTF=1 @{0 946 2}
abil -> term2964 Nt=3 TF=3 maxTF=1 @{0 949 2}
abnorm -> term1433 Nt=1 TF=1 maxTF=1 @{0 956 4}
abort -> term2271 Nt=1 TF=1 maxTF=1 @{0 959 0}
abrupt -> term2870 Nt=1 TF=1 maxTF=1 @{0 961 4}
abschrecken -> term3115 Nt=1 TF=1 maxTF=1 @{0 964 2}
absolut -> term3180 Nt=1 TF=1 maxTF=1 @{0 967 0}
abstract -> term3302 Nt=1 TF=1 maxTF=1 @{0 969 6}
abu -> term3826 Nt=1 TF=1 maxTF=1 @{0 972 4}
abus -> term3283 Nt=1 TF=1 maxTF=1 @{0 975 4}
abyei -> term1862 Nt=1 TF=1 maxTF=1 @{0 978 2}
academ -> term3383 Nt=1 TF=1 maxTF=1 @{0 980 6}
academi -> term900 Nt=1 TF=1 maxTF=1 @{0 983 4}
acceler -> term2850 Nt=8 TF=8 maxTF=1 @{0 985 6}
accelerometri -> term3161 Nt=1 TF=1 maxTF=1 @{0 998 4}
accept -> term813 Nt=2 TF=2 maxTF=1 @{0 1001 2}
access -> term1244 Nt=4 TF=4 maxTF=1 @{0 1006 4}
accid -> term1935 Nt=1 TF=1 maxTF=1 @{0 1015 0}
accident -> term1865 Nt=1 TF=1 maxTF=1 @{0 1017 4}
accommod -> term3461 Nt=1 TF=1 maxTF=1 @{0 1020 0}
account -> term1010 Nt=8 TF=8 maxTF=1 @{0 1023 0}
accumul -> term245 Nt=3 TF=3 maxTF=1 @{0 1040 2}
accuraci -> term2872 Nt=2 TF=2 maxTF=1 @{0 1046 6}
acet -> term4042 Nt=1 TF=1 maxTF=1 @{0 1051 6}
acetamido -> term3895 Nt=1 TF=1 maxTF=1 @{0 1054 6}
acetaminophen -> term3951 Nt=1 TF=1 maxTF=1 @{0 1057 6}
acetonitril -> term5062 Nt=1 TF=1 maxTF=1 @{0 1060 6}
acetylen -> term3813 Nt=5 TF=5 maxTF=1 @{0 1063 6}
achiev -> term3403 Nt=3 TF=3 maxTF=1 @{0 1073 4}
acid -> term1348 Nt=11 TF=13 maxTF=2 @{0 1080 4}
acii -> term3507 Nt=1 TF=1 maxTF=1 @{0 1096 6}
acoust -> term872 Nt=1 TF=1 maxTF=1 @{0 1099 6}
acquisit -> term199 Nt=2 TF=2 maxTF=1 @{0 1102 0}
across -> term1751 Nt=7 TF=7 maxTF=1 @{0 1106 4}
acryl -> term5072 Nt=1 TF=1 maxTF=1 @{0 1120 2}
act -> term139 Nt=8 TF=8 maxTF=1 @{0 1123 2}
action -> term282 Nt=11 TF=11 maxTF=1 @{0 1137 2}
activ -> term6 Nt=49 TF=50 maxTF=2 @{0 1157 2}
activist -> term2337 Nt=1 TF=1 maxTF=1 @{0 1218 1}
actor -> term100 Nt=5 TF=5 maxTF=1 @{0 1220 7}
actuat -> term3158 Nt=4 TF=4 maxTF=1 @{0 1228 7}
ad -> term2585 Nt=6 TF=6 maxTF=1 @{0 1235 5}
adaboost -> term1526 Nt=1 TF=1 maxTF=1 @{0 1248 3}
adapt -> term97 Nt=26 TF=26 maxTF=1 @{0 1250 7}
addit -> term2463 Nt=6 TF=6 maxTF=1 @{0 1287 7}
address -> term235 Nt=7 TF=7 maxTF=1 @{0 1300 5}
adjoin -> term2498 Nt=1 TF=1 maxTF=1 @{0 1313 3}
adjunct -> term2567 Nt=1 TF=1 maxTF=1 @{0 1316 1}
adjust -> term2419 Nt=4 TF=4 maxTF=1 @{0 1318 7}
adl -> term4354 Nt=2 TF=2 maxTF=1 @{0 1327 3}
administr -> term4350 Nt=2 TF=2 maxTF=1 @{0 1331 5}
adolesc -> term2997 Nt=1 TF=1 maxTF=1 @{0 1335 5}
adoleszent -> term4629 Nt=1 TF=1 maxTF=1 @{0 1338 3}
adopt -> term990 Nt=6 TF=6 maxTF=1 @{0 1341 3}
adr -> term4415 Nt=1 TF=1 maxTF=1 @{0 1354 3}
adsorb -> term3611 Nt=1 TF=1 maxTF=1 @{0 1357 3}
adsorpt -> term3580 Nt=6 TF=6 maxTF=1 @{0 1360 3}
adult -> term2713 Nt=2 TF=2 maxTF=1 @{0 1370 3}
advanc -> term648 Nt=8 TF=8 maxTF=1 @{0 1375 7}
advantag -> term227 Nt=2 TF=2 maxTF=1 @{0 1391 1}
advent -> term839 Nt=1 TF=1 maxTF=1 @{0 1395 7}
adventur -> term2769 Nt=1 TF=1 maxTF=1 @{0 1398 1}
adversari -> term1982 Nt=2 TF=2 maxTF=1 @{0 1400 7}
advisori -> term4222 Nt=1 TF=1 maxTF=1 @{0 1406 1}
aerosol -> term2736 Nt=1 TF=1 maxTF=1 @{0 1409 1}
aev -> term2047 Nt=1 TF=1 maxTF=1 @{0 1411 7}
affair -> term32 Nt=3 TF=3 maxTF=1 @{0 1414 3}
affect -> term162 Nt=6 TF=6 maxTF=1 @{0 1420 3}
affin -> term2270 Nt=1 TF=1 maxTF=1 @{0 1432 1}
affluenc -> term1861 Nt=1 TF=1 maxTF=1 @{0 1434 5}
afford -> term3811 Nt=1 TF=1 maxTF=1 @{0 1437 1}
afghanistan -> term190 Nt=2 TF=2 maxTF=1 @{0 1440 1}
afla -> term4412 Nt=1 TF=1 maxTF=1 @{0 1444 5}
africa -> term372 Nt=9 TF=9 maxTF=1 @{0 1447 5}
african -> term1816 Nt=1 TF=1 maxTF=1 @{0 1466 1}
aftermath -> term1745 Nt=2 TF=2 maxTF=1 @{0 1468 5}
ag -> term216 Nt=18 TF=18 maxTF=1 @{0 1471 7}
agcl -> term3648 Nt=1 TF=1 maxTF=1 @{0 1501 5}
agenc -> term570 Nt=4 TF=4 maxTF=1 @{0 1504 5}
agenda -> term2265 Nt=1 TF=1 maxTF=1 @{0 1512 3}
agent -> term144 Nt=21 TF=21 maxTF=1 @{0 1514 7}
aggreg -> term2458 Nt=6 TF=6 maxTF=1 @{0 1547 1}
aggress -> term4741 Nt=1 TF=1 maxTF=1 @{0 1558 1}
agil -> term1810 Nt=1 TF=1 maxTF=1 @{0 1561 1}
agreement -> term2268 Nt=2 TF=2 maxTF=1 @{0 1563 5}
agro -> term831 Nt=1 TF=1 maxTF=1 @{0 1567 7}
agua -> term4067 Nt=1 TF=1 maxTF=1 @{0 1570 1}
ah -> term4454 Nt=1 TF=1 maxTF=1 @{0 1573 1}
ahmad -> term3828 Nt=2 TF=2 maxTF=1 @{0 1576 1}
ahror -> term3780 Nt=1 TF=1 maxTF=1 @{0 1581 3}
ai -> term452 Nt=7 TF=8 maxTF=2 @{0 1584 3}
aid -> term1792 Nt=2 TF=2 maxTF=1 @{0 1599 0}
air -> term578 Nt=3 TF=3 maxTF=1 @{0 1604 2}
aircraft -> term2928 Nt=1 TF=1 maxTF=1 @{0 1611 0}
airflow -> term2614 Nt=2 TF=2 maxTF=1 @{0 1613 6}
airplan -> term2025 Nt=1 TF=1 maxTF=1 @{0 1618 2}
airport -> term1872 Nt=1 TF=1 maxTF=1 @{0 1620 6}
akten -> term2180 Nt=1 TF=1 maxTF=1 @{0 1623 2}
aktienm -> term3484 Nt=1 TF=1 maxTF=1 @{0 1625 6}
aktualit -> term1001 Nt=1 TF=1 maxTF=1 @{0 1628 6}
al -> term126 Nt=48 TF=64 maxTF=5 @{0 1631 0}
alaro -> term3093 Nt=1 TF=1 maxTF=1 @{0 1690 4}
alaska -> term2822 Nt=1 TF=1 maxTF=1 @{0 1693 2}
alb -> term1592 Nt=1 TF=1 maxTF=1 @{0 1696 0}
albtraum -> term1497 Nt=1 TF=1 maxTF=1 @{0 1698 4}
alder -> term5155 Nt=1 TF=1 maxTF=1 @{0 1701 0}
alga -> term3229 Nt=1 TF=1 maxTF=1 @{0 1704 0}
algarv -> term3742 Nt=1 TF=1 maxTF=1 @{0 1706 6}
algarvio -> term4601 Nt=1 TF=1 maxTF=1 @{0 1709 6}
algeria -> term3341 Nt=1 TF=1 maxTF=1 @{0 1712 6}
algerien -> term3925 Nt=3 TF=3 maxTF=1 @{0 1715 4}
algorithm -> term498 Nt=23 TF=23 maxTF=1 @{0 1721 4}
alhambra -> term4245 Nt=1 TF=1 maxTF=1 @{0 1755 2}
ali -> term1060 Nt=4 TF=4 maxTF=1 @{0 1758 2}
alien -> term2278 Nt=2 TF=2 maxTF=1 @{0 1767 2}
alish -> term3719 Nt=1 TF=1 maxTF=1 @{0 1772 4}
alkyl -> term4292 Nt=1 TF=1 maxTF=1 @{0 1775 4}
allah -> term3052 Nt=1 TF=1 maxTF=1 @{0 1778 4}
allaqa -> term4902 Nt=1 TF=1 maxTF=1 @{0 1781 2}
allein -> term2493 Nt=1 TF=1 maxTF=1 @{0 1784 2}
allen -> term2519 Nt=1 TF=1 maxTF=1 @{0 1787 0}
allevi -> term4641 Nt=1 TF=1 maxTF=1 @{0 1789 6}
alli -> term1450 Nt=1 TF=1 maxTF=1 @{0 1792 6}
allianc -> term1756 Nt=1 TF=1 maxTF=1 @{0 1795 2}
alloc -> term233 Nt=4 TF=4 maxTF=1 @{0 1797 6}
almond -> term3941 Nt=1 TF=2 maxTF=2 @{0 1806 4}
alp -> term2962 Nt=1 TF=1 maxTF=1 @{0 1809 5}
alpha -> term2534 Nt=2 TF=2 maxTF=1 @{0 1812 3}
alpin -> term2438 Nt=1 TF=1 maxTF=1 @{0 1817 7}
alt -> term2308 Nt=1 TF=1 maxTF=1 @{0 1820 5}
altern -> term1234 Nt=1 TF=1 maxTF=1 @{0 1823 3}
altmetr -> term4477 Nt=1 TF=1 maxTF=1 @{0 1825 5}
alumina -> term4726 Nt=1 TF=1 maxTF=1 @{0 1828 5}
aluminum -> term3898 Nt=1 TF=1 maxTF=1 @{0 1831 5}
am -> term1733 Nt=11 TF=11 maxTF=1 @{0 1834 5}
amanah -> term4573 Nt=1 TF=1 maxTF=1 @{0 1853 1}
amaz -> term3641 Nt=1 TF=1 maxTF=1 @{0 1856 1}
ambda -> term4295 Nt=1 TF=1 maxTF=1 @{0 1859 1}
ambigu -> term700 Nt=2 TF=2 maxTF=1 @{0 1862 1}
ambit -> term5000 Nt=1 TF=1 maxTF=1 @{0 1866 7}
america -> term19 Nt=9 TF=9 maxTF=1 @{0 1869 7}
american -> term309 Nt=11 TF=11 maxTF=1 @{0 1887 5}
amerika -> term2172 Nt=1 TF=1 maxTF=1 @{0 1905 7}
amidoalkyl -> term3862 Nt=1 TF=1 maxTF=1 @{0 1908 3}
amino -> term4048 Nt=3 TF=3 maxTF=1 @{0 1911 3}
aminoacridinium -> term5019 Nt=1 TF=1 maxTF=1 @{0 1917 3}
aminobenzenethiol -> term4155 Nt=1 TF=1 maxTF=1 @{0 1920 3}
aminobenzo -> term3948 Nt=1 TF=1 maxTF=1 @{0 1923 3}
aminophenyl -> term4020 Nt=2 TF=2 maxTF=1 @{0 1926 3}
aminopyrimidin -> term5129 Nt=1 TF=1 maxTF=1 @{0 1929 5}
aminothiophenol -> term4208 Nt=1 TF=1 maxTF=1 @{0 1932 5}
amman -> term4324 Nt=1 TF=1 maxTF=1 @{0 1935 5}
amount -> term3855 Nt=2 TF=2 maxTF=1 @{0 1938 5}
amplif -> term2799 Nt=1 TF=1 maxTF=1 @{0 1942 7}
amplitud -> term3235 Nt=1 TF=1 maxTF=1 @{0 1945 5}
ampute -> term3039 Nt=2 TF=2 maxTF=1 @{0 1948 3}
amstetten -> term1587 Nt=1 TF=1 maxTF=1 @{0 1953 3}
analizi -> term1258 Nt=1 TF=1 maxTF=1 @{0 1955 7}
analog -> term2192 Nt=2 TF=2 maxTF=1 @{0 1958 1}
analogu -> term2651 Nt=2 TF=2 maxTF=1 @{0 1962 7}
analys -> term410 Nt=16 TF=16 maxTF=1 @{0 1967 7}
analysen -> term1973 Nt=1 TF=1 maxTF=1 @{0 1996 1}
analysi -> term113 Nt=171 TF=173 maxTF=2 @{0 1998 5}
analyt -> term357 Nt=13 TF=13 maxTF=1 @{0 2163 3}
analytisch -> term2058 Nt=2 TF=2 maxTF=1 @{0 2185 1}
analyz -> term470 Nt=21 TF=21 maxTF=1 @{0 2190 3}
anatomi -> term2657 Nt=2 TF=2 maxTF=1 @{0 2223 7}
anaweg -> term2650 Nt=1 TF=1 maxTF=1 @{0 2229 1}
anaylsi -> term4994 Nt=1 TF=1 maxTF=1 @{0 2231 7}
anchor -> term4437 Nt=1 TF=1 maxTF=1 @{0 2234 7}
ancient -> term4180 Nt=3 TF=3 maxTF=1 @{0 2237 7}
andalu -> term4066 Nt=1 TF=1 maxTF=1 @{0 2244 7}
ander -> term4788 Nt=1 TF=1 maxTF=1 @{0 2247 7}
anger -> term678 Nt=1 TF=1 maxTF=1 @{0 2250 7}
anglophon -> term1050 Nt=1 TF=1 maxTF=1 @{0 2253 1}
angri -> term2814 Nt=1 TF=1 maxTF=1 @{0 2255 3}
angst -> term2056 Nt=1 TF=1 maxTF=1 @{0 2258 1}
angstkommunik -> term2051 Nt=1 TF=1 maxTF=1 @{0 2260 5}
angustifolia -> term3638 Nt=1 TF=2 maxTF=2 @{0 2263 1}
anh -> term4754 Nt=1 TF=1 maxTF=1 @{0 2266 2}
anhand -> term3601 Nt=2 TF=2 maxTF=1 @{0 2269 2}
anic -> term4291 Nt=1 TF=1 maxTF=1 @{0 2274 4}
aniliden -> term4047 Nt=1 TF=1 maxTF=1 @{0 2277 4}
anilin -> term4017 Nt=2 TF=2 maxTF=1 @{0 2280 4}
anim -> term3994 Nt=1 TF=1 maxTF=1 @{0 2283 6}
animos -> term1347 Nt=1 TF=1 maxTF=1 @{0 2286 6}
anni -> term1105 Nt=1 TF=1 maxTF=1 @{0 2289 2}
annihayah -> term4686 Nt=1 TF=1 maxTF=1 @{0 2291 4}
annot -> term2276 Nt=6 TF=6 maxTF=1 @{0 2294 4}
annual -> term2890 Nt=5 TF=5 maxTF=1 @{0 2307 4}
anomali -> term2750 Nt=3 TF=3 maxTF=1 @{0 2315 4}
anonym -> term225 Nt=4 TF=4 maxTF=1 @{0 2322 4}
ansatz -> term2063 Nt=1 TF=1 maxTF=1 @{0 2329 6}
answer -> term455 Nt=4 TF=4 maxTF=1 @{0 2332 2}
ant -> term3921 Nt=1 TF=1 maxTF=1 @{0 2341 2}
antagon -> term974 Nt=1 TF=1 maxTF=1 @{0 2344 2}
antara -> term4901 Nt=1 TF=1 maxTF=1 @{0 2346 4}
antenna -> term3025 Nt=1 TF=1 maxTF=1 @{0 2349 4}
anthranil -> term5095 Nt=1 TF=1 maxTF=1 @{0 2352 2}
anthropogen -> term2367 Nt=2 TF=2 maxTF=1 @{0 2355 2}
anthropolog -> term3656 Nt=1 TF=1 maxTF=1 @{0 2359 6}
anthropomorph -> term3163 Nt=1 TF=1 maxTF=1 @{0 2362 6}
anti -> term117 Nt=37 TF=37 maxTF=1 @{0 2365 4}
antibacteri -> term3734 Nt=6 TF=6 maxTF=1 @{0 2402 6}
anticanc -> term3981 Nt=1 TF=1 maxTF=1 @{0 2413 0}
anticip -> term3178 Nt=1 TF=1 maxTF=1 @{0 2416 0}
anticipatori -> term154 Nt=1 TF=1 maxTF=1 @{0 2418 6}
anticonvuls -> term4576 Nt=1 TF=1 maxTF=1 @{0 2420 2}
antimicrobi -> term3863 Nt=1 TF=1 maxTF=1 @{0 2423 2}
antiqu -> term4368 Nt=3 TF=3 maxTF=1 @{0 2426 2}
antisemit -> term2636 Nt=2 TF=2 maxTF=1 @{0 2432 2}
antiskid -> term2927 Nt=1 TF=1 maxTF=1 @{0 2437 2}
antiterroreinheiten -> term2171 Nt=1 TF=1 maxTF=1 @{0 2440 0}
antiterrorism -> term1273 Nt=2 TF=2 maxTF=1 @{0 2442 4}
antitumor -> term5149 Nt=1 TF=1 maxTF=1 @{0 2447 6}
antonio -> term2775 Nt=1 TF=1 maxTF=1 @{0 2450 6}
antwort -> term2174 Nt=1 TF=1 maxTF=1 @{0 2453 4}
anwendbarkeit -> term4563 Nt=1 TF=1 maxTF=1 @{0 2456 0}
anwendung -> term2124 Nt=1 TF=1 maxTF=1 @{0 2459 0}
anxieti -> term922 Nt=2 TF=2 maxTF=1 @{0 2461 4}
aocial -> term4885 Nt=1 TF=1 maxTF=1 @{0 2466 2}
aphor -> term4875 Nt=1 TF=1 maxTF=1 @{0 2469 2}
apida -> term2083 Nt=1 TF=1 maxTF=1 @{0 2472 2}
apocalyps -> term983 Nt=2 TF=3 maxTF=2 @{0 2474 6}
apocryph -> term4329 Nt=1 TF=1 maxTF=1 @{0 2480 1}
apolog -> term1956 Nt=1 TF=1 maxTF=1 @{0 2483 1}
apostasi -> term3759 Nt=1 TF=1 maxTF=1 @{0 2485 5}
app -> term494 Nt=2 TF=2 maxTF=1 @{0 2488 5}
appl -> term4505 Nt=1 TF=1 maxTF=1 @{0 2492 3}
appli -> term437 Nt=9 TF=9 maxTF=1 @{0 2495 3}
applic -> term213 Nt=56 TF=58 maxTF=2 @{0 2511 5}
approach -> term239 Nt=76 TF=78 maxTF=2 @{0 2587 1}
approb -> term722 Nt=2 TF=2 maxTF=1 @{0 2677 1}
approch -> term3026 Nt=1 TF=1 maxTF=1 @{0 2681 7}
approxim -> term1797 Nt=8 TF=8 maxTF=1 @{0 2684 5}
april -> term1156 Nt=1 TF=1 maxTF=1 @{0 2699 5}
aptitud -> term88 Nt=2 TF=2 maxTF=1 @{0 2701 7}
aqqa -> term4786 Nt=1 TF=1 maxTF=1 @{0 2703 5}
aqueou -> term3854 Nt=3 TF=3 maxTF=1 @{0 2706 5}
ar -> term3295 Nt=2 TF=2 maxTF=1 @{0 2713 3}
arab -> term264 Nt=34 TF=35 maxTF=2 @{0 2718 5}
arabi -> term3825 Nt=1 TF=1 maxTF=1 @{0 2764 0}
arabia -> term492 Nt=2 TF=2 maxTF=1 @{0 2767 0}
arabien -> term4273 Nt=1 TF=1 maxTF=1 @{0 2771 6}
arabisch -> term4677 Nt=1 TF=1 maxTF=1 @{0 2774 6}
arabischen -> term3791 Nt=4 TF=4 maxTF=1 @{0 2777 6}
arafat -> term486 Nt=1 TF=1 maxTF=1 @{0 2786 0}
arama -> term4582 Nt=1 TF=1 maxTF=1 @{0 2788 0}
arapskih -> term3702 Nt=1 TF=1 maxTF=1 @{0 2791 0}
arava -> term4942 Nt=1 TF=1 maxTF=1 @{0 2794 0}
arbeit -> term1901 Nt=1 TF=1 maxTF=1 @{0 2797 0}
arbeiten -> term1825 Nt=1 TF=1 maxTF=1 @{0 2799 4}
arbitrari -> term2931 Nt=1 TF=1 maxTF=1 @{0 2802 0}
archaeolog -> term4022 Nt=3 TF=3 maxTF=1 @{0 2804 6}
archeri -> term4702 Nt=1 TF=1 maxTF=1 @{0 2811 6}
archetyp -> term980 Nt=1 TF=1 maxTF=1 @{0 2814 6}
architectur -> term276 Nt=16 TF=17 maxTF=2 @{0 2817 0}
archiv -> term4296 Nt=1 TF=1 maxTF=1 @{0 2841 1}
arctic -> term2486 Nt=2 TF=2 maxTF=1 @{0 2844 1}

In [12]:
term = "attack" 
index.getLexicon()[term].toString() #Gibt die Ergebnisse für einen einzigen Term aus

'term177 Nt=94 TF=94 maxTF=1 @{0 3258 2}'

In [13]:
#Which term occur the most?

term_freq_dict = {}  #Erstellen eines Dict. Schlüssel=Term , Wert=Anzahl des Vorkommens

for kv in index.getLexicon():
    term_freq_dict[kv.getKey()] = kv.getValue().frequency

In [14]:
#sort all terms from the index in descending order
term_freq_dict_sorted = sorted(term_freq_dict.items(), key=lambda x: x[1], reverse=True) #Nicht nach alphabetisch sondern die nach Häufigkeit des Terms ordnen

In [15]:
top_k = 30 #gibt die 30 häufigstens Terme in gestemmter Form aus
term_freq_dict_sorted[:top_k]

[('extrem', 639),
 ('islam', 415),
 ('terror', 400),
 ('terrorist', 357),
 ('model', 234),
 ('network', 204),
 ('analysi', 173),
 ('extremum', 168),
 ('base', 155),
 ('us', 146),
 ('2', 137),
 ('und', 131),
 ('studi', 127),
 ('seek', 120),
 ('climat', 115),
 ('system', 113),
 ('der', 106),
 ('upper', 105),
 ('detect', 99),
 ('social', 98),
 ('chang', 96),
 ('attack', 94),
 ('de', 93),
 ('synthesi', 93),
 ('global', 90),
 ('control', 88),
 ('approach', 78),
 ('effect', 74),
 ('extremist', 73),
 ('precipit', 71)]

In [16]:
#define our search engine
search_engine = pt.BatchRetrieve(index, wmodel="Tf") #erstellt ein Retriever Objekt, das für die Suche im Index zuständig ist
                                                     #wmodel (weigt model) --> Nach Welchem Modell soll die Relevanz gewichtet werden (TF, TF-IDF, BM25)
                                                     #bei TF: Je häufiger ein Term in einem Dokument vorkommt, desto höher soll das Dokument gewichtet sein

/tmp/ipykernel_4644/1673605724.py:2: DeprecationWarning: Call to deprecated class BatchRetrieve. (use pt.terrier.Retriever() instead) -- Deprecated since version 0.11.0.
  search_engine = pt.BatchRetrieve(index, wmodel="Tf") #erstellt ein Retriever Objekt, das für die Suche im Index zuständig ist

In [17]:
search_engine.search("terrorism") #jetzt is die Suchmaschine definiert und wir können nach bestimmten Termen suchen

,qid,docid,docno,rank,score,query
0,1,61,https://www.bibsonomy.org/bibtex/22ee56728eeba...,0,2.0,terrorism
1,1,62,https://www.bibsonomy.org/bibtex/20b361a7cf25b...,1,2.0,terrorism
2,1,73,https://www.bibsonomy.org/bibtex/2b84b0f833814...,2,2.0,terrorism
3,1,74,https://www.bibsonomy.org/bibtex/21ed633534dcb...,3,2.0,terrorism
4,1,75,https://www.bibsonomy.org/bibtex/212bb9d775607...,4,2.0,terrorism
...,...,...,...,...,...,...
382,1,2074,https://www.bibsonomy.org/bibtex/2031f80c7f6ac...,382,1.0,terrorism
383,1,2108,https://www.bibsonomy.org/bibtex/27271541d9248...,383,1.0,terrorism
384,1,2294,https://www.bibsonomy.org/bibtex/276cb7ee3d22a...,384,1.0,terrorism
385,1,2330,https://www.bibsonomy.org/bibtex/2c895142934fc...,385,1.0,terrorism
386,1,2708,https://www.bibsonomy.org/bibtex/288338a237464...,386,1.0,terrorism

In [18]:
search_engine.search("terrorism network")

,qid,docid,docno,rank,score,query
0,1,99,https://www.bibsonomy.org/bibtex/262ecf348e821...,0,3.0,terrorism network
1,1,258,https://www.bibsonomy.org/bibtex/2f3d1899b5d58...,1,3.0,terrorism network
2,1,282,https://www.bibsonomy.org/bibtex/209e829188ea9...,2,3.0,terrorism network
3,1,289,https://www.bibsonomy.org/bibtex/2a474f8e526b6...,3,3.0,terrorism network
4,1,871,https://www.bibsonomy.org/bibtex/2651436f4ef07...,4,3.0,terrorism network
...,...,...,...,...,...,...
545,1,2609,https://www.bibsonomy.org/bibtex/23c46012e580a...,545,1.0,terrorism network
546,1,2642,https://www.bibsonomy.org/bibtex/2dda9498c0ff6...,546,1.0,terrorism network
547,1,2689,https://www.bibsonomy.org/bibtex/25526974e7c92...,547,1.0,terrorism network
548,1,2708,https://www.bibsonomy.org/bibtex/288338a237464...,548,1.0,terrorism network
549,1,2753,https://www.bibsonomy.org/bibtex/2df752ac3b1f4...,549,1.0,terrorism network

In [19]:
#what do we need for inverse document frequency? -->TF-IDF Gewichtung soll berücksichten dass seltene Terme stärker gewichtet werden 
#als weniger seltene wie "und, das, ist"

In [20]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

In [21]:
#stem the term its base form
stem = stemmer.stem("violence")
stem

'violenc'

In [22]:
#wie oft kommt das gestemmte Wort vor?
lexicon = index.getLexicon()
lexicon[stem].getDocumentFrequency()

7

In [23]:
index.getCollectionStatistics().numberOfDocuments

2790

In [24]:
#Funktion zur BErechnung des IDF-Wertes

def get_idf_for_term(term, index):
    lex = index.getLexicon()
    stemmed_term = stemmer.stem(term)
    if not stemmed_term in lex:
        return

    lex_entry = lex[stemmed_term]
    
    df_term = lex_entry.getDocumentFrequency()
    N = index.getCollectionStatistics().numberOfDocuments
    
    #inverse Dokumentenfrequenz
    idf = N/df_term
    #logarithmus, damit die Relevanz nicht proportional berechnet wird
    log_idf = np.emath.logn(10, idf)
    
    return log_idf

In [25]:
get_idf_for_term("violence", index)

2.6005061632593405

In [26]:
#define your own tf_idf method here:

def calc_tf_idf(query, docno, index):
    #remember that tfidf is the product of two components
    #hint: the tf model search result contains tf frequencies
    return 0

In [27]:
search_engine_tfidf = pt.BatchRetrieve(index, wmodel="TF_IDF")

/tmp/ipykernel_4644/2880449899.py:1: DeprecationWarning: Call to deprecated class BatchRetrieve. (use pt.terrier.Retriever() instead) -- Deprecated since version 0.11.0.
  search_engine_tfidf = pt.BatchRetrieve(index, wmodel="TF_IDF")

In [28]:
search_engine_tfidf.search("violece")

Empty DataFrame
Columns: [qid, docid, docno, rank, score, query]
Index: []

In [29]:
df_bibsonomy.columns

Index(['id', 'label', 'author', 'type', 'date', 'year', 'search_term', 'tags',
       'description', 'changeDate', 'url', 'pub-type', 'publisher', 'docno',
       'text'],
      dtype='object')

In [30]:
#transform dataframe into list of dictionaries
ter_dict = df_bibsonomy.to_dict(orient='records')

In [31]:
ter_dict #Das ter_dict ist eine Liste [], in der jeder einzelne Eintrag ein Dictionary ist {}

[{'id': 'https://www.bibsonomy.org/bibtex/22e03edf1449f8bd34a2f6f8a13229bd5/ijtsrd',
  'label': 'Food Terrorism',
  'author': ['Matthew N. O. Sadiku | Sarhan M. Musa | Tolulope J. Ashaolu'],
  'type': 'Publication',
  'date': '2019-07-04 12:16:18',
  'year': '2019',
  'search_term': 'terrorism',
  'tags': ['terrorism', 'biological', 'defense', 'food', 'agro'],
  'description': '',
  'changeDate': '2019-07-04 12:16:18',
  'url': 'https://www.ijtsrd.com/other-scientific-research-area/other/23642/food-terrorism/matthew-n-o-sadiku',
  'pub-type': 'article',
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/22e03edf1449f8bd34a2f6f8a13229bd5/ijtsrd',
  'text': 'Food Terrorism'},
 {'id': 'https://www.bibsonomy.org/bibtex/26a182024b6dbd37445d219533eb5e87a/ijtsrd',
  'label': 'How does Terrorism Effect on Business and Relation Between Countries',
  'author': ['S. Raju Pooja Prof. Sidharth'],
  'type': 'Publication',
  'date': '2018-09-11 08:26:02',
  'year': '2017',
  'search_term': 'terrorism',
  'tags': ['Business',
   '(IB)',
   'Terrorism',
   'business',
   'International',
   'issues'],
  'description': '',
  'changeDate': '2018-10-02 11:01:26',
  'url': 'http://www.ijtsrd.com/management/international-business-issues/4598/how-does-terrorism-effect-on-business-and-relation--between-countries/prof-sidharth-s-raju',
  'pub-type': 'article',
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/26a182024b6dbd37445d219533eb5e87a/ijtsrd',
  'text': 'How does Terrorism Effect on Business and Relation Between Countries'},
 {'id': 'https://www.bibsonomy.org/bibtex/201c2fea8172ad598c18d7dd1c4754547/ijtsrd',
  'label': 'Money Transfer Regulation and the Fight against Terrorism Related Activities in Cameroon',
  'author': ['Lukong Alban Bongwong'],
  'type': 'Publication',
  'date': '2020-10-03 11:41:39',
  'year': '2020',
  'search_term': 'terrorism',
  'tags': ['Other', 'transfer', 'terrorism', 'corruption', 'Funds'],
  'description': '',
  'changeDate': '2020-10-03 11:41:39',
  'url': 'https://www.ijtsrd.com/other-scientific-research-area/other/33109/money-transfer-regulation-and-the-fight-against-terrorism-related-activities-in-cameroon/lukong-alban-bongwong',
  'pub-type': 'article',
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/201c2fea8172ad598c18d7dd1c4754547/ijtsrd',
  'text': 'Money Transfer Regulation and the Fight against Terrorism Related Activities in Cameroon'},
 {'id': 'https://www.bibsonomy.org/bibtex/2273978ed4446aad86fa30528e130388f/droessler',
  'label': 'State terrorism in Latin America : Chile, Argentina, and international human rights',
  'author': ['Thomas Wright'],
  'type': 'Publication',
  'date': '2015-07-23 15:15:26',
  'year': '2007',
  'search_term': 'terrorism',
  'tags': ['außenpolitik',
   'usa',
   'menschenrechte',
   'politik',
   'lateinamerika',
   'terrorismus'],
  'description': 'State Terrorism in Latin America: Chile, Argentina, and International Human Rights Latin American Silhouettes: Amazon.de: Thomas Wright: Fremdsprachige Bücher',
  'changeDate': '2020-11-20 13:41:20',
  'url': 'http://www.amazon.de/State-Terrorism-Latin-America-International/dp/0742537218/ref=sr_1_4?ie=UTF8&qid=1437657198&sr=8-4&keywords=state-sponsored+terrorism',
  'pub-type': 'book',
  'publisher': 'Rowman & Littlefield',
  'docno': 'https://www.bibsonomy.org/bibtex/2273978ed4446aad86fa30528e130388f/droessler',
  'text': 'State terrorism in Latin America : Chile, Argentina, and international human rights'},
 {'id': 'https://www.bibsonomy.org/bibtex/2adba8d1854b2cd1775a9cf07c1dabf61/ijtsrd',
  'label': 'The Role of Extradition Treaties in Crime Management and Combating Terrorism',
  'author': ['AdishiEric OlukaNduka Lucas'],
  'type': 'Publication',
  'date': '2018-09-01 12:55:37',
  'year': '2018',
  'search_term': 'terrorism',
  'tags': ['Extradition',
   'Crime',
   'Terrorism',
   'treaties',
   'challenges',
   'Political',
   'security',
   'Science',
   'Global'],
  'description': '',
  'changeDate': '2018-10-02 11:01:26',
  'url': 'http://www.ijtsrd.com/humanities-and-the-arts/political-science/9475/the-role-of-extradition-treaties-in-crime-management-and-combating-terrorism/adishi-eric',
  'pub-type': 'article',
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/2adba8d1854b2cd1775a9cf07c1dabf61/ijtsrd',
  'text': 'The Role of Extradition Treaties in Crime Management and Combating Terrorism'},
 {'id': 'https://www.bibsonomy.org/bibtex/262f7bd0bcaf8af43b17cbd6a410f3d9a/nosebrain',
  'label': 'Introducing the global terrorism database',
  'author': ['Gary LaFree', 'Laura Dugan'],
  'type': 'Publication',
  'date': '2020-03-25 11:58:40',
  'year': '2007',
  'search_term': 'terrorism',
  'tags': ['dataset', 'database', 'killbert', 'terrorism'],
  'description': '',
  'changeDate': '2020-03-25 11:58:40',
  'url': '',
  'pub-type': 'article',
  'publisher': 'Taylor & Francis',
  'docno': 'https://www.bibsonomy.org/bibtex/262f7bd0bcaf8af43b17cbd6a410f3d9a/nosebrain',
  'text': 'Introducing the global terrorism database'},
 {'id': 'https://www.bibsonomy.org/bibtex/218c8c359b1d6b04e2d84bdd0fb638471/fbw_hannover',
  'label': 'What makes a terrorist',
  'author': ['Alan B. Krueger'],
  'type': 'Publication',
  'date': '2009-08-21 12:22:28',
  'year': '2007',
  'search_term': 'terrorism',
  'tags': ['Terrorismus',
   'Economic_aspects',
   'Wirtschaftssoziologie',
   'Kriminalpolitik',
   'Terrorism',
   'Kriminalitätsökonomik',
   'Wirtschaft',
   'Terrorists',
   'Wirtschaftspsychologie',
   'Terrorist',
   'Politische_Gewalt'],
  'description': '',
  'changeDate': '2009-08-21 12:23:09',
  'url': 'http://gso.gbv.de/DB=2.1/CMD?ACT=SRCHA&SRT=YOP&IKT=1016&TRM=ppn+529478641&sourceid=fbw_bibsonomy',
  'pub-type': 'book',
  'publisher': 'Princeton Univ. Press',
  'docno': 'https://www.bibsonomy.org/bibtex/218c8c359b1d6b04e2d84bdd0fb638471/fbw_hannover',
  'text': 'What makes a terrorist'},
 {'id': 'https://www.bibsonomy.org/bibtex/2abaf760a38643b89e172a64f24587cf0/meneteqel',
  'label': 'The "Moro Affair" - Left-Wing Terrorism and Conspiracy in Italy in the late 1970s',
  'author': ['Tobias Hof'],
  'type': 'Publication',
  'date': '2019-04-26 00:41:22',
  'year': '2013',
  'search_term': 'terrorism',
  'tags': ['Aldo_Moro',
   'conspiracy',
   'terrorism',
   'Italy',
   'secret_services',
   'conspiracy_theories'],
  'description': '',
  'changeDate': '2019-04-26 00:41:22',
  'url': 'http://www.ssoar.info/ssoar/handle/document/38769',
  'pub-type': 'article',
  'publisher': 'HSR (GESIS Leibniz Institute for the Social Sciences)',
  'docno': 'https://www.bibsonomy.org/bibtex/2abaf760a38643b89e172a64f24587cf0/meneteqel',
  'text': 'The "Moro Affair" - Left-Wing Terrorism and Conspiracy in Italy in the late 1970s'},
 {'id': 'https://www.bibsonomy.org/bibtex/29b576de17b6c47ba8e33cc00f963c412/mikaelbook',
  'label': 'U.S. Libraries and the "War on Terrorism"',
  'author': ['Mark Hudson'],
  'type': 'Publication',
  'date': '2021-08-25 12:31:13',
  'year': '2004',
  'search_term': 'terrorism',
  'tags': ['library', 'usa', 'terrorism'],
  'description': 'U.S. Libraries and the "War on Terrorism" - New Politics',
  'changeDate': '2021-08-25 12:31:13',
  'url': '',
  'pub-type': 'article',
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/29b576de17b6c47ba8e33cc00f963c412/mikaelbook',
  'text': 'U.S. Libraries and the "War on Terrorism"'},
 {'id': 'https://www.bibsonomy.org/bibtex/2cfb2db051d7715b8905549c219a58c42/ijtsrd',
  'label': 'Terrorism Problems and Solutions With Special Reference to India',
  'author': ['Dr. Deep Kumar Srivastava'],
  'type': 'Publication',
  'date': '2022-08-13 08:44:04',
  'year': '2022',
  'search_term': 'terrorism',
  'tags': ['-'],
  'description': '',
  'changeDate': '2022-08-13 08:44:04',
  'url': 'https://www.ijtsrd.com/other-scientific-research-area/other/50308/terrorism-problems-and-solutions--with-special-reference-to-india/dr-deep-kumar-srivastava',
  'pub-type': 'article',
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/2cfb2db051d7715b8905549c219a58c42/ijtsrd',
  'text': 'Terrorism Problems and Solutions With Special Reference to India'},
 {'id': 'https://www.bibsonomy.org/bibtex/2797a8f734e34b0fa4307b88fdd4def99/fbw_hannover',
  'label': 'Dealing with terrorism',
  'author': ['Bruno S. Frey'],
  'type': 'Publication',
  'date': '2009-08-21 12:21:08',
  'year': '2005',
  'search_term': 'terrorism',
  'tags': ['Sozioökonomisches_System',
   'Terrorismus',
   'Alternative',
   'Bekämpfung',
   'Economic_aspects',
   'Prävention',
   'Terrorism',
   'Social_aspects',
   'Politisches_System',
   'Politische_Gewalt',
   'Prevention'],
  'description': '',
  'changeDate': '2009-08-21 12:21:09',
  'url': 'http://gso.gbv.de/DB=2.1/CMD?ACT=SRCHA&SRT=YOP&IKT=1016&TRM=ppn+50305951X&sourceid=fbw_bibsonomy',
  'pub-type': 'book',
  'publisher': 'Elgar',
  'docno': 'https://www.bibsonomy.org/bibtex/2797a8f734e34b0fa4307b88fdd4def99/fbw_hannover',
  'text': 'Dealing with terrorism'},
 {'id': 'https://www.bibsonomy.org/bibtex/249f6ddb9b7697d7b3ea08deaa7ff4c98/tciarli',
  'label': 'Another day, another dollar: Enterprise resilience under terrorism\n\tin developing countries',
  'author': ['Oana Branzei', 'Samer Abdelnour'],
  'type': 'Publication',
  'date': '2013-01-08 19:41:52',
  'year': '2010',
  'search_term': 'terrorism',
  'tags': ['imported', 'conflict'],
  'description': '',
  'changeDate': '2013-01-08 19:42:02',
  'url': 'http://search.proquest.com/docview/356549598?accountid=14182',
  'pub-type': 'article',
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/249f6ddb9b7697d7b3ea08deaa7ff4c98/tciarli',
  'text': 'Another day, another dollar: Enterprise resilience under terrorism\n\tin developing countries'},
 {'id': 'https://www.bibsonomy.org/bibtex/21622559711a44e2bf997a0511f339952/oudman',
  'label': 'Terrorism & Radicalization; an overview',
  'author': ['Sergei Oudman'],
  'type': 'Publication',
  'date': '2021-01-08 14:50:56',
  'year': '2020',
  'search_term': 'terrorism',
  'tags': ['myown'],
  'description': '',
  'changeDate': '2021-01-08 14:50:56',
  'url': 'https://www.ciris.info/panoply-journal-volume-1/',
  'pub-type': 'article',
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/21622559711a44e2bf997a0511f339952/oudman',
  'text': 'Terrorism & Radicalization; an overview'},
 {'id': 'https://www.bibsonomy.org/bibtex/2b3c3a3d57f79c515488115f433d747ee/jrennstich',
  'label': 'Terrorism and guerrilla warfare: Forecasts and remedies',
  'author': ['Richard L. Clutterbuck'],
  'type': 'Publication',
  'date': '2010-03-02 17:25:53',
  'year': '1990',
  'search_term': 'terrorism',
  'tags': ['drug', 'warfare', 'terrorism', 'trafficking', 'irregular'],
  'description': '',
  'changeDate': '2010-03-02 17:27:42',
  'url': '',
  'pub-type': 'book',
  'publisher': 'Routledge',
  'docno': 'https://www.bibsonomy.org/bibtex/2b3c3a3d57f79c515488115f433d747ee/jrennstich',
  'text': 'Terrorism and guerrilla warfare: Forecasts and remedies'},
 {'id': 'https://www.bibsonomy.org/bibtex/29ecd0d91240756fb1370faffb6d21c43/smicha',
  'label': 'Terrorist backlash, terrorism mitigation, and policy delegation',
  'author': ['Kevin Siqueira', 'Todd Sandler'],
  'type': 'Publication',
  'date': '2008-04-28 13:05:01',
  'year': '2007',
  'search_term': 'terrorism',
  'tags': ['Terrorism'],
  'description': '',
  'changeDate': '2008-04-28 13:05:27',
  'url': 'http://www.sciencedirect.com/science/article/B6V76-4N25VRG-1/1/8dfaf3a8b15027f4c204f7ca1b1da44d',
  'pub-type': 'article',
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/29ecd0d91240756fb1370faffb6d21c43/smicha',
  'text': 'Terrorist backlash, terrorism mitigation, and policy delegation'},
 {'id': 'https://www.bibsonomy.org/bibtex/21622559711a44e2bf997a0511f339952/cirisorg',
  'label': 'Terrorism & Radicalization; an overview',
  'author': ['Sergei Oudman'],
  'type': 'Publication',
  'date': '2021-01-08 12:48:26',
  'year': '2020',
  'search_term': 'terrorism',
  'tags': ['myown'],
  'description': '',
  'changeDate': '2024-01-10 12:35:45',
  'url': 'https://www.ciris.info/panoply/index.php/journal/article/view/39',
  'pub-type': 'article',
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/21622559711a44e2bf997a0511f339952/cirisorg',
  'text': 'Terrorism & Radicalization; an overview'},
 {'id': 'https://www.bibsonomy.org/bibtex/210f273d1867dbd5e0b171882349a62c5/ijtsrd',
  'label': 'Prognosis of Theories of Intelligence in Counter Terrorism The Case of the Northwestern Nigeria',
  'author': ['Jonjon Emmanuel'],
  'type': 'Publication',
  'date': '2021-06-08 12:45:25',
  'year': '2021',
  'search_term': 'terrorism',
  'tags': ['Prognosis',
   'Intelligence',
   'Terrorism',
   'insecurity',
   'counter-terrorism'],
  'description': '',
  'changeDate': '2021-06-08 12:45:25',
  'url': 'https://www.ijtsrd.com/humanities-and-the-arts/sociology/40057/prognosis-of-theories-of-intelligence-in-counterterrorism-the-case-of-the-northwestern-nigeria/jonjon-emmanuel',
  'pub-type': 'article',
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/210f273d1867dbd5e0b171882349a62c5/ijtsrd',
  'text': 'Prognosis of Theories of Intelligence in Counter Terrorism The Case of the Northwestern Nigeria'},
 {'id': 'https://www.bibsonomy.org/bibtex/2493d114a483004f9aa65dafc4f2a218d/kperezlopez',
  'label': 'Preference Modification vs. Incentive Manipulation as Tools of Terrorist Recruitment: the Role of Cultures',
  'author': ['Michael Munger'],
  'type': 'Publication',
  'date': '2006-04-29 21:40:47',
  'year': '2005',
  'search_term': 'terrorism',
  'tags': ['club_goods', 'recruitment', 'culture', 'CSS739', 'terrorism'],
  'description': 'Munger explores the role that culture plays in defining choices, as for example, those faced by one being recruited to terrorism.  He spends most of the paper defining culture, its meaning and origins, using game theory illustrations of his ideas.   He discusses the differences between “institutions,” which are long-lived and entrenched, regardless of whether or not they are optimal, and “organizations,” which are the always-optimal responses to the system embodied by the institutions.  At the end of the article, he shows how this explains why terrorism may be a rational organizational response to the one’s institutional situation, and how it shapes the incentives of the game we play with terrorists.',
  'changeDate': '2006-04-29 21:40:47',
  'url': 'http://psweb.sbs.ohio-state.edu/intranet/cppe/ ',
  'pub-type': 'article',
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/2493d114a483004f9aa65dafc4f2a218d/kperezlopez',
  'text': 'Preference Modification vs. Incentive Manipulation as Tools of Terrorist Recruitment: the Role of Cultures'},
 {'id': 'https://www.bibsonomy.org/bibtex/230ac0d748fd7378bf3a428058b7214f5/jbwolman',
  'label': 'Shamir on Terrorism (1943)',
  'author': ['Yitzhak Shamir'],
  'type': 'Publication',
  'date': '2010-06-28 00:43:21',
  'year': '1988',
  'search_term': 'terrorism',
  'tags': ['Israeli', 'Shamir,', 'terrorism', 'Yitzhak'],
  'description': '',
  'changeDate': '2010-06-28 00:43:21',
  'url': 'http://www.jstor.org/stable/3012112',
  'pub-type': 'article',
  'publisher': 'Middle East Research and Information Project',
  'docno': 'https://www.bibsonomy.org/bibtex/230ac0d748fd7378bf3a428058b7214f5/jbwolman',
  'text': 'Shamir on Terrorism (1943)'},
 {'id': 'https://www.bibsonomy.org/bibtex/227631331c858099a071b55e558a0bffa/cmcneile',
  'label': 'Global Physics: From Percolation to Terrorism, Guerilla Warfare and Clandestine Activities',
  'author': ['Serge Galam'],
  'type': 'Publication',
  'date': '2019-02-23 22:09:48',
  'year': '2004',
  'search_term': 'terrorism',
  'tags': ['percolation'],
  'description': '',
  'changeDate': '2019-02-23 22:15:27',
  'url': 'http://dx.doi.org/10.1016/j.physa.2003.08.035',
  'pub-type': 'article',
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/227631331c858099a071b55e558a0bffa/cmcneile',
  'text': 'Global Physics: From Percolation to Terrorism, Guerilla Warfare and Clandestine Activities'},
 {'id': 'https://www.bibsonomy.org/bibtex/21669cd64c813ae2e3889e18d28bac97e/mhermans',
  'label': 'The Media War on Terrorism',
  'author': ['Philip Hammond'],
  'type': 'Publication',
  'date': '2007-04-06 10:50:16',
  'year': '2003',
  'search_term': 'terrorism',
  'tags': ['terrorism', 'media'],
  'description': '',
  'changeDate': '2007-04-06 10:50:18',
  'url': 'http://www.jc2m.co.uk/Issue1/Hammond.pdf',
  'pub-type': 'article',
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/21669cd64c813ae2e3889e18d28bac97e/mhermans',
  'text': 'The Media War on Terrorism'},
 {'id': 'https://www.bibsonomy.org/bibtex/21e3feaf7dca7db42b448a16350b9e6a5/meneteqel',
  'label': "Do NSA's Bulk Surveillance Programs Stop Terrorists?",
  'author': ['Peter Bergen',
   'David Sterman',
   'Emily Schneider',
   'Bailey Cahall'],
  'type': 'Publication',
  'date': '2014-01-19 12:31:57',
  'year': '2014',
  'search_term': 'terrorism',
  'tags': ['usa',
   'terrorism',
   'surveillance',
   'nsa',
   'new_america_foundation'],
  'description': '',
  'changeDate': '2014-01-19 12:31:57',
  'url': 'http://www.newamerica.net/publications/policy/do_nsas_bulk_surveillance_programs_stop_terrorists',
  'pub-type': 'techreport',
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/21e3feaf7dca7db42b448a16350b9e6a5/meneteqel',
  'text': "Do NSA's Bulk Surveillance Programs Stop Terrorists?"},
 {'id': 'https://www.bibsonomy.org/bibtex/289973c1e6879da420f7f66fac38a2a0f/spwilcox',
  'label': 'Aptitude for Destruction, Volume 2: Case Studies of Organizational\r\n\tLearning in Five Terrorist Groups',
  'author': ['Brian A. Jackson',
   'John C. Baker',
   'Peter Chalk',
   'Kim Cragin',
   'John V. Parachini',
   'Horacio R. Trujillo'],
  'type': 'Publication',
  'date': '2006-04-05 05:44:05',
  'year': '2005',
  'search_term': 'terrorism',
  'tags': ['CSS739', 'terrorism', 'organizational_learning'],
  'description': '',
  'changeDate': '2006-04-05 05:44:05',
  'url': 'http://www.rand.org/pubs/monographs/2005/RAND_MG332.pdf',
  'pub-type': 'book',
  'publisher': 'RAND',
  'docno': 'https://www.bibsonomy.org/bibtex/289973c1e6879da420f7f66fac38a2a0f/spwilcox',
  'text': 'Aptitude for Destruction, Volume 2: Case Studies of Organizational\r\n\tLearning in Five Terrorist Groups'},
 {'id': 'https://www.bibsonomy.org/bibtex/2e42188f114b199f644e8034c54471c57/spwilcox',
  'label': 'On complex adaptive systems and terrorism',
  'author': ['E. Ahmed1', 'A. S. Elgazzar', 'A. S. Hegazi1'],
  'type': 'Publication',
  'date': '2006-04-06 05:06:51',
  'year': '2005',
  'search_term': 'terrorism',
  'tags': ['imported', 'CSS739', 'terrorism'],
  'description': '',
  'changeDate': '2006-04-06 05:06:51',
  'url': 'http://www.citebase.org/cgi-bin/fulltext?format=application/pdf&identifier=oai:arXiv.org:nlin/0501032',
  'pub-type': 'article',
  'publisher': nan,
  'docno': 'https://www.bibsonomy.org/bibtex/2e42188f114b199f644e8034c54471c57/spwilcox',
  'text': 'On complex adaptive systems and terrorism'},
 {'id': 'https://www.bibsonomy.org/bibtex/2758537333834fa8482347d18616a93ac/jrennstich',
  'label': 'Political terrorism: A new guide to actors, authors, concepts, data bases, theories, and literature',
  'author': ['Alex Peter Schmid', 'A. J. Jongman', 'Michael Stohl'],
  'type': 'Publication',
  'date': '2010-03-02 17:25:53',
  'year': '1988',
  'search_term': 'terrorism',
  'tags': ['terrorism'],
  'description': '',
  'changeDate': '2010-03-02 17:28:34',
  'url': '',
  'pub-type': 'book',
  'publisher': 'North-Holland',
  'docno': 'https://www.bibsonomy.org/bibtex/2758537333834fa8482347d18616a93ac/jrennstich',
  'text': 'Political terrorism: A new guide to actors, authors, concepts, data bases, theories, and literature'},

In [32]:
index_folder_mult = "/home/tim/Schreibtisch/2024-25-Data_Librarian-Reschop_Tim/Modul_2-1/violece_index_mult"

fields=['docno', 'text', 'tags', 'description'] #fields: Eine Liste von Feldern, die indiziert werden sollen (Dokumentnummer, Text, Tags, Beschreibung).


indexer_mult = pt.IterDictIndexer(index_folder_mult, meta={'docno': 200, 'text': 4096}, fields=True, text_attrs=fields, overwrite=True) #Ein Indexer, der mit einem Dictionary von Dokumenten arbeitet. 
                                                                                                        #Die Dokumente in diesem Fall sind wahrscheinlich als Dictionary gespeichert (z. B. 
                                                                                                        #Eine Metainformation, in der die maximale Länge für die Felder docno und text angegeben wird, 
                                                                                                        #(z. B. dass docno maximal 200 Zeichen und text maximal 4096 Zeichen lang sein darf).
index_ref_mult = indexer_mult.index(ter_dict) #Hier wird auf ein Dictionary oder eine Sammlung von Dokumenten verwiesen, die indiziert werden sollen. 
                                                             #Es wird angenommen, dass es ein Dictionary ist, in dem jedes Dokument die Felder docno, text, tags und description enthält.

print(f"path to our index: {index_ref_mult.toString()}")

path to our index: /home/tim/Schreibtisch/2024-25-Data_Librarian-Reschop_Tim/Modul_2-1/violece_index_mult/data.properties

In [33]:
index_mult = pt.IndexFactory.of(index_ref_mult) #erstellen des neunen Indexes

In [34]:
print(index_mult.getCollectionStatistics().toString())

Number of documents: 2790
Number of terms: 7149
Number of postings: 48107
Number of fields: 4
Number of tokens: 54838
Field names: [docno, text, tags, description]
Positions:   false

In [35]:
search_engine_mult = pt.BatchRetrieve(index_mult, wmodel="TF_IDF")

/tmp/ipykernel_4644/495383578.py:1: DeprecationWarning: Call to deprecated class BatchRetrieve. (use pt.terrier.Retriever() instead) -- Deprecated since version 0.11.0.
  search_engine_mult = pt.BatchRetrieve(index_mult, wmodel="TF_IDF")

In [36]:
res = search_engine_mult.search("terrorism")
res

,qid,docid,docno,rank,score,query
0,1,110,https://www.bibsonomy.org/bibtex/23a9422bcfa97...,0,2.621963,terrorism
1,1,8,https://www.bibsonomy.org/bibtex/29b576de17b6c...,1,2.504214,terrorism
2,1,20,https://www.bibsonomy.org/bibtex/21669cd64c813...,2,2.428528,terrorism
3,1,16,https://www.bibsonomy.org/bibtex/210f273d1867d...,3,2.422616,terrorism
4,1,0,https://www.bibsonomy.org/bibtex/22e03edf1449f...,4,2.351712,terrorism
...,...,...,...,...,...,...
449,1,462,https://www.bibsonomy.org/bibtex/2dfa9f402760d...,449,0.986185,terrorism
450,1,880,https://www.bibsonomy.org/bibtex/24099898410e6...,450,0.986185,terrorism
451,1,435,https://www.bibsonomy.org/bibtex/20a84e04dbfd6...,451,0.973275,terrorism
452,1,319,https://www.bibsonomy.org/bibtex/2c3fcb19c7e91...,452,0.936497,terrorism
453,1,986,https://www.bibsonomy.org/bibtex/289e44bc0700d...,453,0.902398,terrorism

In [37]:
#Daten Speichern
pickle.dump(df_bibsonomy, open("/home/tim/Schreibtisch/2024-25-Data_Librarian-Reschop_Tim/Modul_2-1/violence_pubs.pkl", "wb"))

In [38]:
%pip install streamlit

Requirement already satisfied: streamlit in /home/tim/anaconda3/lib/python3.12/site-packages (1.37.1)
Requirement already satisfied: altair<6,>=4.0 in /home/tim/anaconda3/lib/python3.12/site-packages (from streamlit) (5.0.1)
Requirement already satisfied: blinker<2,>=1.0.0 in /home/tim/anaconda3/lib/python3.12/site-packages (from streamlit) (1.6.2)
Requirement already satisfied: cachetools<6,>=4.0 in /home/tim/anaconda3/lib/python3.12/site-packages (from streamlit) (5.3.3)
Requirement already satisfied: click<9,>=7.0 in /home/tim/anaconda3/lib/python3.12/site-packages (from streamlit) (8.1.7)
Requirement already satisfied: numpy<3,>=1.20 in /home/tim/anaconda3/lib/python3.12/site-packages (from streamlit) (1.26.4)
Requirement already satisfied: packaging<25,>=20 in /home/tim/anaconda3/lib/python3.12/site-packages (from streamlit) (24.1)
Requirement already satisfied: pandas<3,>=1.3.0 in /home/tim/anaconda3/lib/python3.12/site-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<11,>=7.1.0 in /home/tim/anaconda3/lib/python3.12/site-packages (from streamlit) (10.4.0)
Requirement already satisfied: protobuf<6,>=3.20 in /home/tim/anaconda3/lib/python3.12/site-packages (from streamlit) (4.25.3)
Requirement already satisfied: pyarrow>=7.0 in /home/tim/anaconda3/lib/python3.12/site-packages (from streamlit) (16.1.0)
Requirement already satisfied: requests<3,>=2.27 in /home/tim/anaconda3/lib/python3.12/site-packages (from streamlit) (2.32.3)
Requirement already satisfied: rich<14,>=10.14.0 in /home/tim/anaconda3/lib/python3.12/site-packages (from streamlit) (13.7.1)
Requirement already satisfied: tenacity<9,>=8.1.0 in /home/tim/anaconda3/lib/python3.12/site-packages (from streamlit) (8.2.3)
Requirement already satisfied: toml<2,>=0.10.1 in /home/tim/anaconda3/lib/python3.12/site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.3.0 in /home/tim/anaconda3/lib/python3.12/site-packages (from streamlit) (4.11.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /home/tim/anaconda3/lib/python3.12/site-packages (from streamlit) (3.1.43)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /home/tim/anaconda3/lib/python3.12/site-packages (from streamlit) (0.8.0)
Requirement already satisfied: tornado<7,>=6.0.3 in /home/tim/anaconda3/lib/python3.12/site-packages (from streamlit) (6.4.1)
Requirement already satisfied: watchdog<5,>=2.1.5 in /home/tim/anaconda3/lib/python3.12/site-packages (from streamlit) (4.0.1)
Requirement already satisfied: jinja2 in /home/tim/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit) (3.1.4)
Requirement already satisfied: jsonschema>=3.0 in /home/tim/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: toolz in /home/tim/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit) (0.12.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /home/tim/anaconda3/lib/python3.12/site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/tim/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/tim/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/tim/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/tim/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /home/tim/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/tim/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/tim/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (2024.8.30)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/tim/anaconda3/lib/python3.12/site-packages (from rich<14,>=10.14.0->streamlit) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/tim/anaconda3/lib/python3.12/site-packages (from rich<14,>=10.14.0->streamlit) (2.15.1)
Requirement already satisfied: smmap<5,>=3.0.1 in /home/tim/anaconda3/lib/python3.12/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/tim/anaconda3/lib/python3.12/site-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.3)
Requirement already satisfied: attrs>=22.2.0 in /home/tim/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/tim/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /home/tim/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in /home/tim/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.10.6)
Requirement already satisfied: mdurl~=0.1 in /home/tim/anaconda3/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.0)
Requirement already satisfied: six>=1.5 in /home/tim/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.3.0->streamlit) (1.16.0)
Note: you may need to restart the kernel to use updated packages.